### ISSUE TITLE
JitterTerm with celerite2

### ISSUE THREAD

**Issue by pilchat** [exoplanet-dev/celerite2#16]
Hi,

is there any celerite.terms.JitterTerm in celerite2?

Thanks

**Comment by dfm** [comment]
There is not - you should just add your jitter to the diagonal directly:

```python
kernel = celerite2.terms....
gp = celerite2.GaussianProcess(kernel)
gp.compute(t, diag=yerr ** 2 + jitter ** 2)
```

**Comment by pilchat** [comment]
ok, you can close the issue if you want. thanks! :)
