### ISSUE TITLE
Getting started tutorial fails with Theano

### ISSUE THREAD

**Issue by jvines** [exoplanet-dev/celerite2#20]
Hi,

I'm following your tutorial, and in the pymc3 section the code fails with this error:

```
Exception: ('Compilation failed (return status=254): clang-10: error: unable to execute command: Segmentation fault: 11. clang-10: error: dsymutil command failed due to signal (use -v to see invocation). ', '[Elemwise{true_div,no_inplace}(<TensorType(float64, row)>, <TensorType(float64, matrix)>)]')
```

I've not found how to fix it and it seems it's related to Theano.

I'm using python 3.7 and OS X Mojave 10.14.6

Do you have any idea how to fix this??

Thanks.

**Comment by dfm** [comment]
I have seen this a few times recently. You're right that it's a deeper theano issue, but I'm happy to try to help debug it. Did you install using conda? If so, can you make a fresh environment and post the steps required to reproduce your issue?

**Comment by jvines** [comment]
I did install with conda. I'll make a fresh environment and do it from scratch and let you know.

In the meantime, I modeled with multinest 3 stitched TESS light curve sectors for a star with the RotationTerm to detrend the data but when I do the prediction it eats up all my memory and crashes, is this normal?? I want to detrend the light curve so I can't bin down for the prediction, what's your experience with this??

Thanks

**Comment by dfm** [comment]
Some prediction operations are memory intensive, but just computing the mean prediction at the data points shouldn't be. Exactly which operations are you currently running?

**Comment by jvines** [comment]
I run this:

```python
def set_params(cube, gp):
    """Set the GP parameter vector."""
    mflux, jitter, sigma = cube[0], cube[1], cube[2]
    period, q0, dq, f = cube[3], cube[4], cube[5], cube[6]
    gp.mean = mflux
    gp.kernel = terms.RotationTerm(sigma=sigma, period=period,
                                   Q0=q0, dQ=dq, f=f)
    gp.compute(times_oot, diag=flux_err_oot ** 2 + jitter ** 2, quiet=True)
    return gp

theta = np.median(posterior_samples, axis=0)
gp = set_params(theta, gp)

gp.compute(pdctimes23, yerr=pdcfluxes_error23**2 + theta[1]**2)

mean, var = gp.predict(pdcfluxes23 - theta[0], return_var=True)
```

where pdcfluxes23 is the relative flux of 2 out of the 3 sectors stitched together and pdctimes23 are the respective timestamps. That consumes all my memory and eventually crashes.

**Comment by dfm** [comment]
Yeah - `return_var` will require a lot of memory. I'd recommend just using the mean and ignoring the variance. I assume that you're using the variance because you want to propagate uncertainties in the detrending? Are you sure that it's much different than just adding the yerrs and jitter in quadrature? I bet you can approximate it well enough using that or by just evaluating the variance at one point and using that everywhere.

**Comment by jvines** [comment]
Ah, perfect. I see, I figure it won't be much different so I'll try that. Thank you!!
