### ISSUE TITLE
Theano Version Issues Between Exoplanet 0.4.4 and Celerite2

### ISSUE THREAD

**Issue by ceyrox** [exoplanet-dev/celerite2#30]
**Describe the bug**
The exoplanet software, when conda installed, automatically adds the package theano-pymc, which seems to conflict with my installed version of theano. When I have, without exoplanet, theano version 1.0.5 installed on my computer, the command

`from celerite2.theano import  terms`

executes normally. After a conda installation of exoplanet version 0.4.4, theano-pymc version 1.1.5 is automatically installed. Then, the command

`from celerite2.theano import terms` 

ends in an attribute error, I have attached a picture. This is all done on a freshly created conda environment, with minimal packages installed. My advisor has also been able to recreate this problem on a completely separate machine.

**To Reproduce**

 It is not necessary to create a fresh environment, but that has the best hopes for reproduction:

`conda create -n myenv python`

Then install any files one needs, I prefer using Jupyter Notebook, and so I run

`pip install notebook`

Install celerite2 and theano:

`conda install -c conda-forge theano
python -m pip install -U celerite2
`

Then running the following command in either a jupyter notebook or any short python script should terminate successfully:

`from celerite2.theano import terms`

Next, installing any version of exoplanet seems to override this. I did it with the latest version:

`conda install -c conda-forge exoplanet
`

Now when I run the command

`from celerite2.theano import terms`

The code ends in an Attribute error, a picture of which is attached.

<img width="1086" alt="exoplanet_bug" src="https://user-images.githubusercontent.com/59852423/108916315-ec277680-75e2-11eb-924a-cc596751f42a.png">

**Expected behavior**
I expect the command 

`from celerite2.theano import terms`

To execute without error.

**Your setup (please complete the following information):**
 - Version of exoplanet: 0.4.4 (though I have tried multiple versions)
 - Operating system: macOS Catalina 10.15.7
 - Python version & installation method (pip, conda, etc.): Python version 3.7.10 (though I have tried multiple version)

**Additional context**
With this setup, I have installed and successfully run Celerite2 tutorials, provided they do not use the directory celerite.theano.

Additionally, I have run exactly copied exoplanet tutorials. Those that do not use celerite2 run to accurate completion. Those that use celerite2 end in failure.

**Comment by dfm** [comment]
I've moved this to `celerite2` because the initial issue is a `celerite2` issue not an `exoplanet` issue.

@LucaNap: I'm sorry that you're having trouble with this, but I'm certainly not forcing you to use anything! I'm working on fixing this issue (that was only opened 2 weeks ago), but this project has a lot of dependencies that have been breaking like crazy recently and I'm just one person doing what I can so please have some patience.

**Comment by LucaNap** [comment]
@dfm sorry I did not mean to disrespect you.. I guess this shows that english is not my first language! Thanks for your work

**Comment by dfm** [comment]
@LucaNap: Thanks for your response and no hard feelings! I'm hoping to have an updated release in the next day or two (see #29).

**Comment by Astromorph** [comment]
Thanks for reporting this issue @ceyrox. I have been encountering similar problems with:

`from celerite2.theano import terms`

My PhD at the European Southern Observatory focuses on stellar activity filtering using Gaussian Processes towards exoplanet detection and characterisation. So celerite2 + PyMC3 should be perfect for that work.
Please @dfm let us know when you pushed a compatible version of celerite2 with exoplanet 0.4.4 and its latest dependencies.

P.S.: Cheers to the developer team of celerite2 and exoplanet, great work! 👌

**Comment by dfm** [comment]
I've just updated celerite2 and exoplanet on PyPI so

```bash
python -m pip install -U celerite2 exoplanet
```

should deliver versions that are all compatible. You might want to make sure that the `theano` and `theano-pymc` packages are uninstalled first because there are issues with colliding namespaces between those two packages.

I'm going to close this issue for now, but please comment if you continue having these issues and I can reopen as needed!
