### ISSUE TITLE
Help with JAX, PyTorch, and TensorFlow bindings

### ISSUE THREAD

**Issue by dfm** [exoplanet-dev/celerite2#4]
I don't really use these libraries (yet!) so I'm not sure exactly what the use cases would look like. Any help would be appreciated.

- **JAX** This interface is probably the most mature, but I'd love to add XLA primitives (#1). This would involve working out a traceable forward diff op, I think. More trouble than its worth? Maybe not.
- **PyTorch** The ops all work and are tested, but I don't really understand how `nn.Module`s work so it's probably all a mess.
- **TensorFlow** Lives [in this repo](https://github.com/dfm/celerite2-tensorflow). It doesn't follow the recommended build process, but I think I know where to go with this one. Long run: maybe it can be combined with JAX if we work out the XLA primitive stuff.

**Comment by bmorris3** [comment]
Hi @dfm, 

I'm working with the jax interface and it's great! Quick question: are you still considering supporting forward mode differentiation with jax? I'm trying to use celerite2 in combination with another model optimized for forward diff, so I'm hitting a ` NotImplementedError: Batching rule for 'celerite2_factor_jvp' not implemented` error, which brought me here. Thanks!

**Comment by dfm** [comment]
In fact there was never a plan to support forward diff and the "traceable" op referred to in this issue does exist because that's how jax operates :D Supporting forward diff is not high priority for me, but feel free to open an issue as a feature request making a _specific_ argument for it or I'd be happy to help with a PR if you're feeling ambitious (it would probably not be straightforward).

**Comment by bmorris3** [comment]
Thanks for the context, @dfm! After investigating all morning, I think I was misinterpreting a bug in the model implementation for a forward-mode requirement anyway (long story 😅). So forward diff might not be necessary for me after all. Sorry for the noise.
