### ISSUE TITLE
Damped Random Walk Model?

### ISSUE THREAD

**Issue by 3fon3fonov** [exoplanet-dev/celerite2#45]
This is likely a lame question, but I will shoot.

Which celerite/celerite2 kernel could be used as Damped Random Walk Model? This is a model used for analyzing quasar light curves. My understanding is that this is a GP model, but I can't find such a kernel, and at this point I do not fell confident enough to build it in celerite/celerite2. So what are my alternatives?

**Comment by dfm** [comment]
As discussed in [the celerite paper](https://arxiv.org/abs/1703.09710), the `RealTerm` is a damped random walk/O-U process. I don't find it to be a good choice in most real use cases because of its high-frequency behavior, so I don't generally recommend it, but it's there if you want it!

**Comment by 3fon3fonov** [comment]
You see, I told you that is a lame question. I overlooked this from the paper! OK, I consider this tread as closed, and thanks!

**Comment by dfm** [comment]
It's not lame and no worries!
