### ISSUE TITLE
Jax mean models?

### ISSUE THREAD

**Issue by benjaminpope** [exoplanet-dev/celerite2#48]
Hi Dan,

Just a question - there is a great tutorial on using the numpyro backend with Jax.

Is there any documentation on using jax mean models too? eg any pitfalls with definitions, gradients, jit..

All the best,

Ben

**Comment by dfm** [comment]
I haven't written such a thing and I don't know that I have enough experience to give any real advice. But, yes, any mean model will need to be both reverse mode differentiable and jit-able for use with something like numpyro. Did you have other things in mind?

**Comment by benjaminpope** [comment]
Sorry, question may have answered itself by digging further into celerite2 - I take it we now prefer numpyro for model building rather than the mean function methods in version 1.
