### ISSUE TITLE
Online documentation notebook tutorial rendering issue: "findfont: Generic family 'sans-serif' not found..."

### ISSUE THREAD

**Issue by gully** [exoplanet-dev/celerite2#77]
Hi there 👋  
I noticed the [online documentation](https://celerite2.readthedocs.io/en/latest/tutorials/first/#maximum-likelihood) has a warning about missing font families:
`findfont: Generic family 'sans-serif' not found because none of the following families were found: Liberation Sans`
I see this on Safari and Chrome, so it's not a browser thing, it appears to be embedded in the rendered docs?

The warning repeats 127 times, filling the screen and requiring long scrolls to navigate to the next series of code cells after a cell involving a plot.  

I'm not sure of the cause.  One could imagine the font server coincidentally had downtime the last time the docs were rendered, in which case simply triggering a re-render of RTD could fix the issue.  Probably more complicated than that. 🤷

**Comment by dfm** [comment]
Thanks! Should be fixed when the next docs build finishes.
