### ISSUE TITLE
Fourier conventions for the PSD in the documentation of the SHOTerm

### ISSUE THREAD

**Issue by tovrstra** [exoplanet-dev/celerite2#81]
My apologies for this rather silly question. I'm just learning the basics at the moment. (The following example from celerite 1 already clarified things: https://celerite.readthedocs.io/en/stable/tutorials/normalization/)

The Fourier convention of the PSD is a bit confusing. I assume the factor $1/\sqrt{2\pi}$ is used in the definition of the Fourier transform. It would be helpful to mention this.

The point were it gets really confusing is the documentation of $S_0$, which seems to be inconsistent with the factor $\sqrt{2/\pi}$ in the docstring of the [SHOTerm](https://celerite2.readthedocs.io/en/latest/api/python/#celerite2.terms.SHOTerm). According to the docstring, $S_0$ is "the power at $\omega=0$". Does the wording "the power at" have a special interpretation, other than $S(0)$?

It could also be helpful to mention the integrated autocorrelation time in the documentation of the SHOTerm, which is $2/Q \omega_0$, if I'm not mistaken.

Sorry for stumbling over these little things, and thanks for the nice implementation.

**Comment by dfm** [comment]
Thanks for the questions and suggestions! The conventions are discussed [in the celerite paper](https://arxiv.org/abs/1703.09710), but I agree that it could be useful to include more info in the docs. I don't have the capacity to add anything like that right now, but I'd be happy to review a pull request! :D

**Comment by tovrstra** [comment]
The paper is indeed clarifying everything. I just made a PR.
